# Generated by Django 5.0 on 2023-12-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='COURSE',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enrollmentnumber',
            new_name='ENROLLMENTNUMBER',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='MOBILE',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='NAME',
        ),
    ]
