# Generated by Django 5.0 on 2023-12-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='MOBILE',
            field=models.CharField(max_length=10),
        ),
    ]
